enum AuthStatus { LOGGED_IN, LOGGED_OUT, NOTFOUND, REGISTERED }
enum ApiStatus { UNKNOWN, LOADING, NOT_AUTHORIZED, SUCCESSFUL, ERROR }
enum Service { CHAT, LOGIN }
enum HeaderTypes { AUTHENTICATED, NON_AUTHENTICATED, FOR_AUTHENTICATION }
enum Method { GET, POST, PUT, DELETE }
